// rankings-loader.js
// This file loads ranking data from Subsystem A (JSON file)

async function loadRankingsFromFile() {
    console.log('📊 Loading rankings from Subsystem A...');
    
    try {
        // Try to load the JSON file generated by Subsystem A
        const response = await fetch('rankings_data.json');
        
        if (!response.ok) {
            throw new Error(`Could not find rankings_data.json (Status: ${response.status})`);
        }
        
        const data = await response.json();
        console.log('✅ Successfully loaded data from Subsystem A!');
        console.log('📅 Generated on:', data.generated);
        console.log('👥 Total players:', data.totalPlayers);
        
        // Update the rankings display
        updateRankingsWithData(data);
        
        // Show success message
        showIntegrationStatus('success', 'Connected to Subsystem A - Data loaded successfully!');
        
    } catch (error) {
        console.error('❌ Failed to load from Subsystem A:', error);
        showIntegrationStatus('error', 'Subsystem A not connected - Using fallback data');
        
        // Use fallback data if file doesn't exist
        useFallbackData();
    }
}

function updateRankingsWithData(data) {
    // Update Most Active tab
    if (data.categories && data.categories.active) {
        updateRankingTab('active', data.categories.active);
    }
    
    // Update High Score tab
    if (data.categories && data.categories.highscore) {
        updateRankingTab('highscore', data.categories.highscore);
    }
    
    // Update Box Jumps tab
    if (data.categories && data.categories.boxjumps) {
        updateRankingTab('boxjumps', data.categories.boxjumps);
    }
}

function updateRankingTab(tabType, players) {
    // Find the tab container
    const container = document.getElementById('rankings-container');
    if (!container) return;
    
    // Check if this tab is currently active
    const activeTab = document.querySelector('.ranking-tab.active');
    const currentTabType = activeTab ? activeTab.getAttribute('data-type') : 'active';
    
    // Only update if this is the active tab
    if (currentTabType === tabType) {
        displayRankings(players, tabType);
    }
}

function showIntegrationStatus(status, message) {
    // Create or update status indicator
    let statusDiv = document.getElementById('integration-status');
    
    if (!statusDiv) {
        // Create status div if it doesn't exist
        statusDiv = document.createElement('div');
        statusDiv.id = 'integration-status';
        statusDiv.style.margin = '10px 0';
        statusDiv.style.padding = '10px';
        statusDiv.style.borderRadius = '5px';
        statusDiv.style.fontWeight = 'bold';
        
        // Insert after rankings tabs
        const rankingsSection = document.getElementById('rankings');
        if (rankingsSection) {
            rankingsSection.insertBefore(statusDiv, document.getElementById('rankings-container'));
        }
    }
    
    statusDiv.style.backgroundColor = status === 'success' ? 'rgba(40, 167, 69, 0.2)' : 'rgba(220, 53, 69, 0.2)';
    statusDiv.style.border = status === 'success' ? '2px solid #28a745' : '2px solid #dc3545';
    statusDiv.style.color = status === 'success' ? '#28a745' : '#dc3545';
    statusDiv.innerHTML = `
        <div style="display: flex; align-items: center; gap: 10px;">
            <i class="bi ${status === 'success' ? 'bi-check-circle-fill' : 'bi-exclamation-triangle-fill'}"></i>
            <span>${message}</span>
        </div>
    `;
}

function useFallbackData() {
    // Your existing rankings data from the HTML
    const fallbackData = {
        active: [
            { position: 1, name: "nibbler", score: "553 min", badge: "Ultra Active" },
            { position: 2, name: "Killerwbøss", score: "277 min", badge: "Very Active" },
            { position: 3, name: "blzmes", score: "259 min", badge: "Very Active" },
            { position: 4, name: "Macmac Cosme", score: "230 min", badge: "Active" },
            { position: 5, name: "Hibandicam", score: "208 min", badge: "Active" },
            { position: 6, name: "Jandy", score: "194 min", badge: "Active" },
            { position: 7, name: "sobidhi", score: "185 min", badge: "Active" },
            { position: 8, name: "devilmaycry", score: "125 min", badge: "Active" },
            { position: 9, name: "Macmac Cosme", score: "102 min", badge: "Active" },
            { position: 10, name: "eprowy", score: "99 min", badge: "Active" }
        ],
        highscore: [
            { position: 1, name: "cpmpastrana", score: "24,271", badge: "Legend" },
            { position: 2, name: "Lancho", score: "24,121", badge: "Legend" },
            { position: 3, name: "Palfittzk", score: "22,074", badge: "Pro" },
            { position: 4, name: "dehislime", score: "18,908", badge: "Pro" },
            { position: 5, name: "Coneno", score: "17,068", badge: "Pro" },
            { position: 6, name: "sarboss", score: "16,246", badge: "Expert" },
            { position: 7, name: "stickrunner", score: "13,681", badge: "Expert" },
            { position: 8, name: "kitten", score: "12,478", badge: "Expert" },
            { position: 9, name: "eprowy", score: "12,273", badge: "Advanced" },
            { position: 10, name: "zelrlc", score: "12,087", badge: "Advanced" }
        ],
        boxjumps: [
            { position: 1, name: "Coneno", score: "1st Place", badge: "Jump God" },
            { position: 2, name: "Palfitt2k", score: "2nd Place", badge: "Jump Pro" },
            { position: 3, name: "Damman1234", score: "3rd Place", badge: "Jump Pro" },
            { position: 4, name: "eprowy", score: "4th Place", badge: "Jump Expert" },
            { position: 5, name: "stickrunner", score: "5th Place", badge: "Jump Expert" },
            { position: 6, name: "panene2", score: "6th Place", badge: "Jump Expert" },
            { position: 7, name: "Reoruse", score: "7th Place", badge: "Advanced" },
            { position: 8, name: "Soda81", score: "8th Place", badge: "Advanced" },
            { position: 9, name: "sarhoss", score: "9th Place", badge: "Advanced" },
            { position: 10, name: "Lancho", score: "10th Place", badge: "Advanced" }
        ]
    };
    
    // Get current active tab
    const activeTab = document.querySelector('.ranking-tab.active');
    const currentType = activeTab ? activeTab.getAttribute('data-type') : 'active';
    
    // Display fallback data for current tab
    displayRankings(fallbackData[currentType], currentType);
}

// Override the existing displayRankings function or add this one
function displayRankings(rankings, type) {
    const container = document.getElementById('rankings-container');
    if (!container) return;
    
    let html = '';
    
    rankings.forEach((player, index) => {
        let cardClass = 'ranking-card';
        if (index === 0) cardClass += ' gold';
        else if (index === 1) cardClass += ' silver';
        else if (index === 2) cardClass += ' bronze';
        
        let scoreLabel = '';
        switch(type) {
            case 'active': scoreLabel = 'Active Time'; break;
            case 'highscore': scoreLabel = 'High Score'; break;
            case 'boxjumps': scoreLabel = 'Box Jumps'; break;
        }
        
        html += `
            <div class="${cardClass} d-flex align-items-center">
                <div class="ranking-position">${player.position}</div>
                <div class="ranking-avatar">
                    <img src="/images/src1.png" alt="${player.name}" title="${player.name}">
                </div>
                <div class="ranking-info">
                    <div class="ranking-name">${player.name}</div>
                    <div class="ranking-score">${scoreLabel}: ${player.score}</div>
                </div>
                <div class="ranking-badge">${player.badge}</div>
            </div>
        `;
    });
    
    container.innerHTML = html;
}

// Initialize when page loads
document.addEventListener('DOMContentLoaded', function() {
    // Try to load from Subsystem A
    loadRankingsFromFile();
    
    // Override the tab click handlers to refresh data
    setupTabHandlers();
});

function setupTabHandlers() {
    document.querySelectorAll('.ranking-tab').forEach(tab => {
        tab.addEventListener('click', function() {
            // Try to reload data when tab changes
            loadRankingsFromFile();
        });
    });
}